title: "`ambivalent` 🤷🏻‍"
# title: ambivalent
date: last-modified
# date: today
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
# appendix-cite-as: display
favicon: "favicon.svg"
open-graph: true
twitter-card: true
site-url: https://saforem2.github.io/ambivalent
google-scholar: true
citeproc: true
# filters:
#   - lightbox
# lightbox: auto
project:
  render:
    - index.qmd
    - quarto/*.qmd
    # - qmd/**/*.qmd
  type: website
  output-dir: "docs"
  preview:
    port: 4249
author:
  name: "Sam Foreman [[{{< ai orcid >}}]{.orcid-green}](https://orcid.org/0000-0002-9981-0876)"
  url: https://samforeman.me
  email: foremans@anl.gov
  # affiliation: Argonne National Laboratory
  # affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Sam Foreman
   type: webpage
   title: "ambivalent"
   url: https://saforem2.github.io/ambivalent
# execute:
#   # keep-ipynb: true
#   # keep-md: true
#   freeze: auto
metadata-files:
  - _website.yml
  - _format.yml
  # - _reveal.yml
